//
// Created by Levalup.
// L.eval: Let programmer get rid of only work jobs.
//

#ifndef LIBUVCXX_UVCXX_H
#define LIBUVCXX_UVCXX_H

#include "uvcxx/utils/apply.h"
#include "uvcxx/utils/assert.h"
#include "uvcxx/utils/callback.h"
#include "uvcxx/utils/defer.h"
#include "uvcxx/utils/detach.h"
#include "uvcxx/utils/pencil_box.h"
#include "uvcxx/utils/platform.h"
#include "uvcxx/utils/promise.h"
#include "uvcxx/utils/queue.h"
#include "uvcxx/utils/standard.h"
#include "uvcxx/utils/tuple.h"

#include "uvcxx/cxx/buffer.h"
#include "uvcxx/cxx/except.h"
#include "uvcxx/cxx/ref.h"
#include "uvcxx/cxx/string.h"
#include "uvcxx/cxx/to_string.h"
#include "uvcxx/cxx/version.h"
#include "uvcxx/cxx/wrapper.h"

#include "uvcxx/inner/base.h"

#include "uvcxx/async.h"
#include "uvcxx/barrier.h"
#include "uvcxx/buf.h"
#include "uvcxx/check.h"
#include "uvcxx/cond.h"
#include "uvcxx/connect.h"
#include "uvcxx/error.h"
#include "uvcxx/fs.h"
#include "uvcxx/fs_event.h"
#include "uvcxx/fs_poll.h"
#include "uvcxx/getaddrinfo.h"
#include "uvcxx/getnameinfo.h"
#include "uvcxx/handle.h"
#include "uvcxx/idle.h"
#include "uvcxx/key.h"
#include "uvcxx/lib.h"
#include "uvcxx/loop.h"
#include "uvcxx/mutex.h"
#include "uvcxx/once.h"
#include "uvcxx/os.h"
#include "uvcxx/pipe.h"
#include "uvcxx/poll.h"
#include "uvcxx/prepare.h"
#include "uvcxx/process.h"
#include "uvcxx/random.h"
#include "uvcxx/req.h"
#include "uvcxx/rwlock.h"
#include "uvcxx/sem.h"
#include "uvcxx/shutdown.h"
#include "uvcxx/signal.h"
#include "uvcxx/stream.h"
#include "uvcxx/tcp.h"
#include "uvcxx/thread.h"
#include "uvcxx/timer.h"
#include "uvcxx/tty.h"
#include "uvcxx/udp.h"
#include "uvcxx/udp_send.h"
#include "uvcxx/utilities.h"
#include "uvcxx/version.h"
#include "uvcxx/work.h"
#include "uvcxx/write.h"

#endif //LIBUVCXX_UVCXX_H
