name: Build MSVC-std

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-msvc-std:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ windows-latest ]
        build_type: [ Release ]
        cl: [ cl ]
        std: [ '17', '14', '11' ]

    name: "On ${{matrix.os}} cl -std=c++${{matrix.std}}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: friendlyanon/fetch-core-count@v1
        id: cores

      - name: Set output
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure
        run: >
          cmake -B "${{ steps.strings.outputs.build-output-dir }}"
          -DCMAKE_CXX_COMPILER=${{ matrix.cl }}
          -DCMAKE_C_COMPILER=${{ matrix.cl }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DSTD=${{ matrix.std }}
          -S "${{ github.workspace }}"

      - name: Build
        run: >-
          cmake --build "${{ steps.strings.outputs.build-output-dir }}"
          --config ${{ matrix.build_type }}

      - name: Test
        working-directory: "${{ steps.strings.outputs.build-output-dir }}"
        run: ctest --output-on-failure --build-config ${{ matrix.build_type }}
